### ISSUE TITLE
Impossible to access/build the UI via yarn

### ISSUE THREAD

**Issue by anaelleltd** [dappforce/subsocial-web-app#432]
**OS: Windows 10 x64.
NodeJS: 14.17.0
Yarn: 1.22.5**

Whenever I run the command $ yarn build, I get this error.

*yarn run v1.22.5
$ yarn patch && next build
$ ./patch.sh
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.*

I have no idea what exit code 1 is so I checked the docs and it's nothing important. 
I ran an audit, and lots of severe vulnerabilities were found.
I deleted the node_modules folder, reinstalled yarn as per the README.md, but I still got the same error.

Any clue what the issue is? Thanks! :)

**Comment by anaelleltd** [comment]
I somehow found a quick fix by installing yarn globally with $npm install -g yarn to fix the corrupted installation.

Now I get this error about a missing module:
*- C:\Users\atale\subsocial-web-app-master\node_modules\next\dist\bin\next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\atale\subsocial-web-app-master\node_modules\@ledgerhq\hw-transport-node-hid\lib\listenDevices.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\atale\subsocial-web-app-master\node_modules\@ledgerhq\hw-transport-node-hid\lib\TransportNodeHid.js:16:45)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\atale\\subsocial-web-app-master\\node_modules\\@ledgerhq\\hw-transport-node-hid\\lib\\listenDevices.js',
    'C:\\Users\\atale\\subsocial-web-app-master\\node_modules\\@ledgerhq\\hw-transport-node-hid\\lib\\TransportNodeHid.js',
    'C:\\Users\\atale\\subsocial-web-app-master\\node_modules\\@polkadot\\ui-keyring\\ledger\\transportsNode.js',
    'C:\\Users\\atale\\subsocial-web-app-master\\node_modules\\@polkadot\\ui-keyring\\ledger\\index.js',
    'C:\\Users\\atale\\subsocial-web-app-master\\node_modules\\@polkadot\\ui-keyring\\index.js',
    'C:\\Users\\atale\\subsocial-web-app-master\\.next\\server\\pages\\_app.js',
    'C:\\Users\\atale\\subsocial-web-app-master\\node_modules\\next\\dist\\build\\utils.js',
    'C:\\Users\\atale\\subsocial-web-app-master\\node_modules\\next\\dist\\build\\index.js',
    'C:\\Users\\atale\\subsocial-web-app-master\\node_modules\\next\\dist\\cli\\next-build.js',
    'C:\\Users\\atale\\subsocial-web-app-master\\node_modules\\next\\dist\\bin\\next'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.*

Not sure why that happens...
