### ISSUE TITLE
Yarn Not Working on Docker Compose

### ISSUE THREAD

**Issue by connerlambden** [dappforce/subsocial-web-app#462]
Hi, I've tried installing on Debian & MacOS and am getting the following error. Any ideas? I've made sure no other processes are running on port 80.

subsocial-web-ui | yarn run v1.10.1
subsocial-web-ui | $ node export-env.js && next start -p 80
subsocial-web-ui | { Error: listen EADDRINUSE :::80
subsocial-web-ui |     at Server.setupListenHandle [as _listen2] (net.js:1286:14)
subsocial-web-ui |     at listenInCluster (net.js:1334:12)
subsocial-web-ui |     at Server.listen (net.js:1421:7)
subsocial-web-ui |     at Promise (/node_modules/next/dist/server/lib/start-server.js:2:62)
subsocial-web-ui |     at new Promise (<anonymous>)
subsocial-web-ui |     at start (/node_modules/next/dist/server/lib/start-server.js:1:469)
subsocial-web-ui |     at nextStart (/node_modules/next/dist/cli/next-start.js:22:125)
subsocial-web-ui |     at commands.(anonymous function).then.exec (/node_modules/next/dist/bin/next:29:346)
subsocial-web-ui |     at process._tickCallback (internal/process/next_tick.js:68:7)
subsocial-web-ui |     at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
subsocial-web-ui |   errno: 'EADDRINUSE',
subsocial-web-ui |   code: 'EADDRINUSE',
subsocial-web-ui |   syscall: 'listen',
subsocial-web-ui |   address: '::',
subsocial-web-ui |   port: 80 }
subsocial-web-ui | error Command failed with exit code 1.
subsocial-web-ui | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Blazeboard** [comment]
I meet the same problem.
